### ISSUE TITLE
Cant open ad options (Cataclysm Classic)

### ISSUE THREAD

**Issue by focaltad** [leatrix/leatrix-plus#241] opened 2024-12-13 22:34 UTC
### Issue

Ive added the correct version of the 3 ad onsbut it wont let me open the option menus in game

### Game version

Cataclysm Classic

**Comment by leatrix** [comment] 2024-12-13 22:39
Manually go into your addons folder using File Explorer, delete the Leatrix addon folders manually (Leatrix_Plus, Leatrix_Maps, Leatrix_Sounds) then install them again from CurseForge App (the addons with USE THIS ADDON in the title).

**Comment by focaltad** [comment] 2024-12-13 22:47
Did not work

**Comment by leatrix** [comment] 2024-12-13 22:54
- Are the addons enabled in your game menu?
- Do the addons appear as entries in the game options addons menu?
- What happens when you enter /ltp, /ltm or /lts in game?
- Open Leatrix_Plus.lua (in the Leatrix_Plus folder) with Notepad, what is the version and date shown at the top?

**Comment by focaltad** [comment] 2024-12-13 23:10
https://youtu.be/C-VlNzjko7A[](url)

![image](https://github.com/user-attachments/assets/8939345d-3052-46b7-916d-0d2ed1cd8519)

**Comment by leatrix** [comment] 2024-12-13 23:19
Disable all other addons so that the only addons you have enabled are Leatrix addons.  Do they show up then?

**Comment by focaltad** [comment] 2024-12-13 23:23
Yea menu options are showing up on slash commands now

**Comment by leatrix** [comment] 2024-12-13 23:26
Another addon is preventing the Leatrix addons from loading correctly so they are showing up in the addon list but not in the game options addons menu because they aren't loading correctly.  Enable other addons gradually until you find the addon causing the conflict then let me know which one it is.

**Comment by focaltad** [comment] 2024-12-14 00:10
Tsm app helper

**Comment by leatrix** [comment] 2024-12-14 00:31
Not something I normally use but it seems to work fine for me.  If you disable all addons except Leatrix addons, TSM and TSM_AppHelper, does that work?

**Comment by leatrix** [comment] 2024-12-14 09:17
Closing this as it isn't caused by Leatrix addons (since the problem is solved when you disable other addons).  You can still reply to closed issues if you like.

**Closed by leatrix** 2024-12-14 09:17 UTC
