### ISSUE TITLE
Miss some nameplates

### ISSUE THREAD

**Issue by PerfectOua** [leatrix/leatrix-plus#7] opened 2021-01-09 22:31 UTC
Hello,

I was using addon "Plater for nameplates". Then I installed "Leatrix Plus (Shadowlands)" and maybe (I'm not sure, I dont remember) I turned on the option "Class colored frames - Show the player, target and focus frame backgrounds in class color." 

But now I uninstalled all addons and I miss some nameplates (look at the screenshot please). As you can see there is only one nameplate of paladin and no other nameplates of other players.

I tried to delete folders WTF, Interface, Cache. I tried commands "/Console Cvar_reset /Console Cvar_default". Likewise, I checked options in game. Nothing helped.

Is it possible that Leatrix Plus (Shadowlands) made this bug? Or I need to find solution from addon "Plater for nameplates"? Can you please help me to fix it?

![Nameplate](https://user-images.githubusercontent.com/30981401/104109909-2b239600-52db-11eb-8f78-c7fbc205f8c1.jpg)

**Comment by PerfectOua** [comment] 2021-01-09 22:41
I checked my other character and there are all nameplates on it. But again - they are not standard, and I don't have any addon installed now.

![Nameplate 2](https://user-images.githubusercontent.com/30981401/104110046-8013dc00-52dc-11eb-96bb-243da5a3c703.png)

**Comment by leatrix** [comment] 2021-01-09 22:46
The 'Class colored frames' option ('Frames') doesn't modify nameplates.  All is does is color the player, target and focus frames in class color.

The only option that modifies nameplates is 'Combat plates' ('System').  But all that does is automatically toggle the 'nameplateShowEnemies' console variable when combat starts and ends.  It's exactly the same as pressing the V key (without modifier) or toggling the 'Enemy Units (V)' checkbox in the game options ('Names').

Remove the Plater addon if you don't want it as this is likely the culprit.  After that, configure the nameplate settings in the 'Names' section of the game options and that should solve the problem.

**Comment by PerfectOua** [comment] 2021-01-09 22:51
As I wrote before - I deleted all addons and all this screenshots are made with 0 addons installed.

**Comment by leatrix** [comment] 2021-01-09 22:57
Yes, I know.  But Plater may have bade changes to the nameplate settings.  That's why you should check the nameplate settings in the 'Names' section of the game options.

**Comment by leatrix** [comment] 2021-01-11 03:06
Closing as this isn't an issue caused by Leatrix Plus.

**Closed by leatrix** 2021-01-11 03:06 UTC
Labels: help
