### ISSUE TITLE
Leatrix_Plus tried to call the protected function UseContainerItem

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [leatrix/leatrix-plus#125] opened 2022-10-28 12:16 UTC
Steps to reproduce:

1. Check "Disable bag automation" and /reload
2. Purchase any consumable item (Alcohol, for example)
3. Try to consume the consumable items (Right click in bag)
4. Repeat 2nd and 3rd steps several times

Eventually, taint warning dialog will show up.

I've enabled script errors (`/console scriptErrors 1`), but it only shows default Blizzard warning dialog, that suggests disabling the addon.

The only way I was able to _grab_ the stack trace was BugGrabber addon:

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Plus' tried to call the protected function 'UseContainerItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>
```

EDIT: Updated repro steps

**Comment by leatrix** [comment] 2022-10-28 12:26
It seems to work fine for me.

If you disable all other addons, do you still see the taint error?
Which version of LTP are you using (shown top-left in the LTP panel)?

**Comment by 0xfeeddeadbeef** [comment] 2022-10-28 12:40
I reproduced this error with all other addons disabled, and then enabled only BugSack/BugGrabber to get hold of stack trace.

LTP version 10.0.02

**Comment by 0xfeeddeadbeef** [comment] 2022-10-28 12:48
One more detail: My character was standing right next to the merchant (with merchant frame already closed) when I tried to consume an item.

**Comment by leatrix** [comment] 2022-10-28 13:01
This is what I am doing to try to reproduce it.
- Ensure 'Disable bag automation' is checked.
- Ensure the taint log (in the Logs folder) is deleted.
- Reload the UI with /reload (essential to ensure any existing errors in memory are cleared).
- Summon Grand Expedition Yak, right-click Cousin Slowhands to open the vendor window and right-click Four Wind Soju to purchase it then close the vendor window with the cross-box.
- Enter /ltp to open LTP panel then close it with the cross-box.
- Press B to open bags and right-click the Four Wind Soju to consume it.

It works fine with no taint error.  There is no taint file in the Logs folder either.  Also tested doing the above during combat and still no error.  Also tested with all other LTP settings disabled (/ltp wipe then check Disable bag automation and reload).

Is the taint error 100% reproducible for you when doing the above (after a /reload) with all other addons disabled?
Is this a new error with LTP 10.0.02?  Does it work without error in LTP 10.0.01?

**Comment by 0xfeeddeadbeef** [comment] 2022-10-28 14:17
Rolled back to LTP 10.0.01, error still occurs.

**Comment by 0xfeeddeadbeef** [comment] 2022-10-28 14:25
This is content of taint.log file:

```
10/28 18:23:15.973  Global variable ACTIVE_CHAT_EDIT_BOX tainted by Leatrix_Plus - Interface/FrameXML/ChatFrame.lua:4506 ChatEdit_DeactivateChat()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4443 ChatEdit_OnEditFocusLost()
10/28 18:23:15.973      ChatFrame1EditBox:hatFrame.xml:121_OnEditFocusLost()
10/28 18:23:15.973      ChatFrame1EditBox:Hide()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4940 ChatEdit_ClearChat()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:5221 ChatEdit_ParseText()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4883 ChatEdit_SendText()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4919 ChatEdit_OnEnterPressed()
10/28 18:23:15.973      ChatFrame1EditBox:hatFrame.xml:127_OnEnterPressed()
10/28 18:23:15.973  Execution tainted by Leatrix_Plus while reading ACTIVE_CHAT_EDIT_BOX - Interface/FrameXML/ChatFrame.lua:4425 ChatEdit_OnHide()
10/28 18:23:15.973      ChatFrame1EditBox:hatFrame.xml:115_OnHide()
10/28 18:23:15.973      ChatFrame1EditBox:Hide()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4940 ChatEdit_ClearChat()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:5221 ChatEdit_ParseText()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4883 ChatEdit_SendText()
10/28 18:23:15.973      Interface/FrameXML/ChatFrame.lua:4919 ChatEdit_OnEnterPressed()
10/28 18:23:15.973      ChatFrame1EditBox:hatFrame.xml:127_OnEnterPressed()
10/28 18:23:15.973  Interface/FrameXML/ContainerFrame.lua:1579 GetBagID()
10/28 18:23:15.973  An action was blocked because of taint from Leatrix_Plus - UseContainerItem()
10/28 18:23:15.973      Interface/FrameXML/ContainerFrame.lua:1384 ContainerFrameItemButton_OnClick()
10/28 18:23:15.973      Interface/FrameXML/ContainerFrame.lua:1435
```

All settings have been wiped (`/ltp wipe`) and only "Disable bag automation" is checked, no idea why it is accessing chat frames.

**Comment by 0xfeeddeadbeef** [comment] 2022-10-28 17:44
One more curious detail: error does happen when trying to use [Oversized Bobber](https://www.wowhead.com/item=136377/oversized-bobber), but does **not** when using [Shiny Bauble](https://www.wowhead.com/item=6529/shiny-bauble) residing right next to it in the bag.

**Comment by leatrix** [comment] 2022-10-28 18:17
It appears that there is block taint in the slash command system.  Does the taint error only occur for you when you have entered a slash command previously (since you last did a UI reload)?

Steps to reproduce:

- Enable any one addon that has a slash command.  You can use LTP for this or you can use another addon such as Bartender or Demodal.  For this example, I will use Bartender.
- Enter /bt to open Bartender's configuration panel.
- Close bartender's configuration panel with the cross-box.
- Open the world map (M key), hold shift and click any quest to track it.  Or, if it's already being tracked, click it to untrack it.  It doesn't matter which.
- Right-click the General chat tab and click Edit Mode.
- Close Edit Mode with the cross-box.
- Block taint occurs.

Repeat the above without using the slash command and no block taint occurs.

**Comment by 0xfeeddeadbeef** [comment] 2022-10-29 13:40
I was unable to reproduce taint issue by following your steps, but, instead, I was able to cause similar taint(s) without touching any slash commands at all:

```
10/29 04:09:36.603  Execution tainted by Leatrix_Plus while reading LeaPlusGlobalPanel_weatherPanel - Interface/FrameXML/UIParent.lua:3307
10/29 04:09:36.603      securecall()
10/29 04:09:36.603      Interface/FrameXML/UIParent.lua:3347
10/29 04:09:36.603      securecall()
10/29 04:09:36.603      Interface/FrameXML/UIParent.lua:2643 Frame:ShowUIPanel()
10/29 04:09:36.603      Interface/FrameXML/UIParent.lua:2552
10/29 04:09:36.603      Frame:SetAttribute()
10/29 04:09:36.603      Interface/FrameXML/UIParent.lua:3150 ShowUIPanel()
10/29 04:09:36.603      Interface/FrameXML/UnitPopupButtons.lua:481 OnClick()
10/29 04:09:36.603      Interface/FrameXML/UnitPopupShared.lua:148 func()
10/29 04:09:36.603      Interface/SharedXML/UIDropDownMenu.lua:1007 UIDropDownMenuButton_OnClick()
10/29 04:09:36.603      DropDownList1Button15:IDropDownMenuTemplates.xml:136_OnClick()
10/29 04:09:36.603  Interface/FrameXML/ContainerFrame.lua:1579 GetBagID()
10/29 04:09:36.603  An action was blocked because of taint from Leatrix_Plus - UseContainerItem()
10/29 04:09:36.603      Interface/FrameXML/ContainerFrame.lua:1384 ContainerFrameItemButton_OnClick()
10/29 04:09:36.603      Interface/FrameXML/ContainerFrame.lua:1435
```

And another one:

```
10/29 17:26:02.562  Global variable BINDING_NAME_CLICK LeaPlusGlobalFlare9:LeftButton tainted by Leatrix_Plus - Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:9606 ?()
10/29 17:26:02.562      Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:11096
10/29 17:26:02.562  Execution tainted by Leatrix_Plus while reading BINDING_NAME_CLICK LeaPlusGlobalFlare9:LeftButton - Interface/SharedXML/BindingUtil.lua:141
10/29 17:26:02.562      securecallfunction()
10/29 17:26:02.562      Interface/FrameXML/SettingDefinitions/Keybindings.lua:149 CreateSearchableSettings()
10/29 17:26:02.562      Interface/FrameXML/SettingDefinitions/Keybindings.lua:273 registrant()
10/29 17:26:02.562      Interface/SharedXML/Settings/Blizzard_SettingsRegistrar.lua:15
10/29 17:26:02.562      secureexecuterange()
10/29 17:26:02.562      Interface/SharedXML/Settings/Blizzard_SettingsRegistrar.lua:17 callback()
10/29 17:26:02.562      Interface/SharedXML/EventUtil.lua:21
10/29 17:26:02.562      securecallfunction()
10/29 17:26:02.562      Interface/SharedXML/CallbackRegistry.lua:143
10/29 17:26:02.562      secureexecuterange()
10/29 17:26:02.562      Interface/SharedXML/CallbackRegistry.lua:146 TriggerEvent()
10/29 17:26:02.562      Interface/SharedXML/GlobalCallbackRegistry.lua:9
10/29 17:26:02.562  Interface/FrameXML/ContainerFrame.lua:1579 GetBagID()
10/29 17:26:02.562  An action was blocked because of taint from Leatrix_Plus - UseContainerItem()
10/29 17:26:02.562      Interface/FrameXML/ContainerFrame.lua:1384 ContainerFrameItemButton_OnClick()
10/29 17:26:02.562      Interface/FrameXML/ContainerFrame.lua:1435
```

Steps that work 100% of time for me:

1. Completely reset LTP settings (I've deleted saved variables file to be sure)
2. Check "Disable bag automation"
3. Restart the game
4. Visit a drinks vendor
5. Buy several of `[Bottle of Dalaran Noir]` (for example)
6. Open bags using SHIFT+B
7. Chug one `[Bottle of Dalaran Noir]`
8. Close bags using SHIFT+B
9. Open LTP by clicking Minimap button
10. Move between LTP pages randomly, then close it
11. Open bags using SHIFT+B
12. Chug another `[Bottle of Dalaran Noir]`
13. **Repeat steps 5 to 12 couple more times**
14. Blizzard taint error message shows up

**Comment by JyanseiCoding** [comment] 2022-10-29 16:14
Hey! Just tuning in to say that I've encountered the same bug doing random content. I wish I could be more helpful but I have no idea how to recreate it. It happened in instanced content and outside. This happens eventually at some point in every session so far.

```1x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Plus' tried to call the protected function 'UseContainerItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>```

**Comment by leatrix** [comment] 2022-10-30 23:46
Many thanks for the reproducible steps, [0xfeeddeadbeef](https://github.com/0xfeeddeadbeef).

The easiest way to replicate the bug is:

- Open vendor then close vendor.
- Open vendor again and buy alcohol (tested with Bottle of Dalaran Noir).
- Drink alcohol.

If you already have the alcohol in your bag, you don't need to buy it again.

Unfortunately, all I can do at the moment is to disable the option completely so in 10.0.04, the option is unavailable.

**Closed** 2022-10-31 04:36 UTC
Labels: help

**Comment by leatrix** [comment] 2022-10-31 12:47
In 10.0.06.alpha.2, the 'Disable bag automation' option is removed due to problems with Blizzard's code in Dragonflight.  Many thanks for the reports.  If Blizzard fix their game code (unlikely), the option can be added back.

**Comment by leatrix** [comment] 2022-11-04 09:49
In Wow 10.0.2.46479 (release candidate), the block taint issue seems to have been fixed so if it stays that way, the 'Disable bag automation' option can return.

**Comment by leatrix** [comment] 2022-11-04 10:38
So providing there are no issues with it, the 'Disable bag automation' option is back in 10.0.07.alpha.2 but it will only be available in game version 10.0.2 (which is currently a release candidate).

**Comment by leatrix** [comment] 2022-11-04 12:19
And on closer inspection with game version 10.0.2, the taint issues remain so the 'Disable bag automation' option will remain locked.

**Comment by 0xfeeddeadbeef** [comment] 2022-11-06 18:17
I've also encountered taint issues with Altoholic, Handy Notes and TomTom. They became unusable.
I'm guessing we have Blizzard to thank for these too.

**Comment by leatrix** [comment] 2022-11-06 21:01
If it's taint that is there now but wasn't there before, then yes.  All you can do is either live with it or hope that the addon author is able to fix it.

These are the current taint steps for 'Disable bag automation' in 10.0.2:

- Open vendor then close vendor.
- Open vendor again and buy alcohol (tested with Bottle of Dalaran Noir).
- Click one of your bag icons and click Convert to Combined Bag or Convert to separate bags.
- Drink alcohol.
- Block taint occurs.

**Comment by leatrix** [comment] 2022-11-09 01:13
This bug report is related to the issue:
https://github.com/Stanzilla/WoWUIBugs/issues/310

**Comment by KVLtv** [comment] 2022-11-11 13:00
I liked the "Drink alcohol" part... lol!

I've been doing a lot of testing on this, because I author an AddOn that was also given as the source of a taint error, which then eventually brought me to [Stanzilla/WoWUIBugs#310](https://github.com/Stanzilla/WoWUIBugs/issues/310) from [OpenAllBags()](https://wowpedia.fandom.com/wiki/API_OpenAllBags) on [Wowpedia](https://wowpedia.fandom.com/wiki/Wowpedia). When a user of my Addon first brought the error to my attention I too was unable to reproduce the error. However, since that time I have seen that error attributed to my AddOn and a number of other AddOns. Not just the protected function 'UseContainerItem()', but a other protected functions such as 'UseAction()'. Upon reviewing the code of the AddOns blamed for the errors, I found no evidence that the AddOn came even remotely close to calling the functions they were accused of. This is likely the case for Leatrix_Pro as well.

I have a theory which I am toying with at the moment, and that theory revolves around a new method of player interaction event handling introduced in patch 10.0.0. To begin testing my theory I created an AddOn to monitor the new [PLAYER_INTERACTION_MANAGER_FRAME_SHOW](https://wowpedia.fandom.com/wiki/PLAYER_INTERACTION_MANAGER_FRAME_SHOW) and [PLAYER_INTERACTION_MANAGER_FRAME_HIDE](https://wowpedia.fandom.com/wiki/PLAYER_INTERACTION_MANAGER_FRAME_HIDE) events, which supersede many of the previously used interaction events. The AddOn simply reports the firing of either and what event that firing represents based on the Type payload list. I discovered that these two events are very busy events. They also seem to frequently fire their "0", or "None", event Type payload. It is my theory that these two events are somehow responsible for the other AddOns being blamed for causing taint. I may be wrong, but it's only a theory and I had to start somewhere, though I admit at this point I have no idea how to actually prove it. Still, the implementation of this new event handling system and the emergence of widespread AddOn bugs seems like too much of a coincidence not to be related somehow.

My testing hasn't provided any substantial telltales so far, and sometimes an error won't trigger for a long time and seemingly rarely for the what seems to be the same reason. I haven't had as much time as I would like in order to address this issue, but as an AddOn author I believe that we have two choices. One is to hope that Blizzard will correct whatever is causing the wild unexplained taint, and the other is for AddOn authors to find some bullet proof way of securing their AddOns. I realize that the article on Wowpedia about [secure execution and taint](https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting) may lead many to the solution of the latter, but in the meanwhile it makes for frustrated users and authors alike. I'd welcome any thoughts on the matter.

**Comment by KVLtv** [comment] 2022-11-11 17:28
I neglected to state exactly why I have the theory mentioned above. The new events overlap a lot of old events, and though I do suspect the intention is for the new events to replace a slew of the events in the game, as of now the new events and the old events are firing at the same time. Some of the old events have been removed, but sometimes only half way, because most of the events happen in pairs. An example being the the MAIL_SHOW event having been left in, but the MAIL_HIDE event has been removed. Evidence for this is in the current performance of the Blizzard_Receipt AddOn, which does not correctly tell you "You've gained" upon the closing of the mailbox, but will tell you that total if you visit a merchant and simply open and close the merchant window. Their own AddOn still erroneously tries to register the missing MAIL_HIDE event. (You may need to remove all ..\Interface\AddOns to reproduce this anomaly.) The new "PLAYER_INTERACTION" events also seem to fire frivolously for seemingly no reason. My theory is that this confuses the game client and causes the taint.
