### ISSUE TITLE
Adibags error

### ISSUE THREAD

**Issue by leviwesterman** [leatrix/leatrix-plus#35] opened 2021-07-20 15:50 UTC
Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:5328: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
Time: Tue Jul 20 17:49:48 2021
Count: 1
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:5328: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua"]:130: in function <...face\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua"]:367: in function `HookScript'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:5328: in function `HighlightTabs'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:5341: in function `?'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:9121: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:8666>

Locals:

**Comment by leatrix** [comment] 2021-07-20 17:40
The error is referencing the 'Hide chat buttons' option ('Chat') but I don't know why AdiBags would conflict with that option.

I'm not able to reproduce the error so disable all addons except LTP and AdiBags.  Do you still see the error?  If so, what are you doing exactly to cause the error to show?  If not, enable other addons gradually until you can reproduce the error then tell me what addon causes the error to show.

According to the error shown, unchecking 'Hide chat buttons' would solve it but if you can tell me how to reproduce the error, I can look at what's causing it.

**Comment by leatrix** [comment] 2021-08-01 08:06
Closing as no updates for 12 days.

**Closed by leatrix** 2021-08-01 08:06 UTC
Labels: help
